### ISSUE TITLE
Compilation Issues When Building From Source

### ISSUE THREAD

**Issue by LeedsJohn** [leostera/minttea#24]
Hi,

I was interested in contributing to this project but have run into a problem.  I began by creating a fork of this repository and cloning it.  After navigating to my new directory, I ran `opam switch create . --deps-only` to create a new switch and install the dependencies.  However, after running `dune build`, I ran into two errors shown below:

![image](https://github.com/leostera/minttea/assets/94880155/60dcb9ec-c35e-462a-8728-9a48424ba179)

Here is the context for the errors:

```

...
let after = after *. 1_000_000.0 |> Int64.of_float in
let _ = Timer.send_after (self ()) (Timer ref) ~after |> Result.get_ok in
...
```

```
let fps_to_float fps = (1. /. cap fps) *. 1_000. |> Int64.of_float
...
Riot.Timer.send_interval ~every:(fps_to_float fps) (self ()) Tick
...
```

In both of these cases, the time seems to be explicitly converted from a float to an Int64, but `Riot.Timer` seems to expect time intervals to be floats.  Deleting the int to float conversions makes everything build without errors.

I suspect I might have just tried to build this project at the wrong time because it looks like @leostera added in the float to int64 conversions change yesterday :) It seems that once Riot 0.0.8 is released this won't be an issue anymore?  However, I thought I would open an issue to make sure you are aware.  Thanks!

**Comment by JMCavanillas** [comment]
Yes, I got It fixed pinning riot repo I think.

`opam pin add <riot-git-repo> --yes`

**Comment by leostera** [comment]
Thanks for opening the issue! ✨ Yes Mint Tea 0.0.2 is running on Riot 0.0.7 which used floats for the timeouts, but we're moving to int64 in Riot 0.0.8, which is what we're using on the current main branch.

This shouldn't affect _users_ of minttea tho, since the `Set_timeout` command still uses floats. I thought the float precision was enough for TUIs. We may wanna change that to int64 later on.

Once Riot 0.0.8 is published on opam it'll be a little easier. But we can add a note on a CONTRIBUTING.md to explain how to do this.

**Comment by LeedsJohn** [comment]
Great, thanks for your help.

Just so you know, unless I've missed something, there is not currently a CONTRIBUTING.md for this project.  

Also, if anybody else happens to have the same problem, I needed to add `--kind=git` to my `opam pin` command (so my full command was `opam pin add https://github.com/leostera/riot --kind=git --yes`).
